### ISSUE TITLE
Module parse failed: Unexpected token (1201:12)

### ISSUE THREAD

**Issue by egeersoz** [Pablillo92/cron-timezone-convert#1]
Thanks for the library, exactly what I was looking for.

Getting this error during compilation though:
```
./node_modules/crontzconvert/dist/crontzconvert.mjs 1201:12
Module parse failed: Unexpected token (1201:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| );
| function a1(z, M, b) {
>   return z ?? M ?? b;
| }
| function L3(z) {
```

**Comment by egeersoz** [comment]
It looks like the compiler does not like the `??` operators.

**Comment by Pablillo92** [comment]
Hi @egeersoz, what version of node are you using?

**Comment by egeersoz** [comment]
v21.5.0

**Comment by Pablillo92** [comment]
It may be because of your webpack configuration, maybe this link will help you.
[https://stackoverflow.com/questions/33469929/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack-and-b](https://stackoverflow.com/questions/33469929/you-may-need-an-appropriate-loader-to-handle-this-file-type-with-webpack-and-b)
